pragma Singleton
import Quickshell
import Quickshell.Io
import "root:/themes"   // Theme (paleta efetiva = paleta escolhida + overrides pal_*)

// Regenera os arquivos de tema dos apps EXTERNOS a partir da paleta efetiva do
// shell (Theme.*, que já reflete a paleta escolhida e os overrides de cor crua).
// Disparado pelo Settings ao trocar de tema ou cor de paleta (e pelo botão da
// janela de configurações).
//
// Alvos (escreve nos MESMOS arquivos que os apps já incluem -> sem mexer noutras
// linhas de config):
//   kitty   -> ~/.config/kitty/themes/crimson-devil.conf   (include no kitty.conf)
//   rofi    -> ~/.config/rofi/themes/crimson-devil.rasi     (@theme no config.rasi)
//   mango   -> ~/.config/mango/devil-shell/theme.conf       (source= no config.conf)
//   vesktop -> ~/.config/vesktop/themes/devil-shell.css      (habilitar 1x no Vesktop)
//   wlogout -> ~/.config/wlogout/{style.css,layout}          (grade de energia + ações)
//   swaylock-> ~/.config/swaylock/config                     (tela de bloqueio)
//
// Antes de escrever, faz BACKUP do que existir (<arquivo>.bak-<timestamp>). Depois
// recarrega ao vivo: mango (reload_config) e kitty (SIGUSR1 relê o config). rofi lê
// o tema no próximo lançamento; o Vesktop recarrega o CSS sozinho quando habilitado.
Singleton {
    id: root

    // cor -> "#rrggbb"
    function hx(c) { return ("" + c).toLowerCase() }
    // cor -> "rrggbb"
    function rgb(c) { return hx(c).replace("#", "") }
    // cor -> "0xRRGGBBAA" (alfa opaco) p/ o mango
    function mg(c) { return "0x" + rgb(c) + "ff" }
    // cor -> "RRGGBBAA" (swaylock); aa = alfa em hex (ex.: "ff", "cc")
    function sl(c, aa) { return rgb(c) + (aa ? aa : "ff") }
    // cor -> "rgba(r,g,b,a)" (CSS do wlogout)
    function rgbaCss(c, a) {
        const h = rgb(c)
        const r = parseInt(h.substr(0, 2), 16), g = parseInt(h.substr(2, 2), 16), b = parseInt(h.substr(4, 2), 16)
        return "rgba(" + r + "," + g + "," + b + "," + a + ")"
    }

    // ── kitty (themes/crimson-devil.conf) ──
    function kittyContent() {
        const t = Theme
        return "## name: Devil Shell (generated)\n"
            + "## Auto-generated by quickshell. Do not edit by hand.\n\n"
            + "foreground            " + hx(t.text) + "\n"
            + "background            " + hx(t.crust) + "\n"
            + "selection_foreground  " + hx(t.crust) + "\n"
            + "selection_background  " + hx(t.mauve) + "\n\n"
            + "cursor                " + hx(t.red) + "\n"
            + "cursor_text_color     " + hx(t.crust) + "\n\n"
            + "url_color             " + hx(t.peach) + "\n\n"
            + "color0  " + hx(t.base) + "\ncolor8  " + hx(t.surface1) + "\n"
            + "color1  " + hx(t.mauve) + "\ncolor9  " + hx(t.red) + "\n"
            + "color2  " + hx(t.green) + "\ncolor10 " + hx(t.teal) + "\n"
            + "color3  " + hx(t.yellow) + "\ncolor11 " + hx(t.peach) + "\n"
            + "color4  " + hx(t.blue) + "\ncolor12 " + hx(t.sky) + "\n"
            + "color5  " + hx(t.maroon) + "\ncolor13 " + hx(t.pink) + "\n"
            + "color6  " + hx(t.teal) + "\ncolor14 " + hx(t.sky) + "\n"
            + "color7  " + hx(t.text) + "\ncolor15 " + hx(t.rosewater) + "\n\n"
            + "active_tab_foreground    " + hx(t.crust) + "\n"
            + "active_tab_background     " + hx(t.mauve) + "\n"
            + "active_tab_font_style     bold\n"
            + "inactive_tab_foreground  " + hx(t.subtext0) + "\n"
            + "inactive_tab_background   " + hx(t.base) + "\n"
            + "inactive_tab_font_style   normal\n"
            + "tab_bar_background        " + hx(t.crust) + "\n\n"
            + "active_border_color    " + hx(t.red) + "\n"
            + "inactive_border_color  " + hx(t.surface1) + "\n"
            + "bell_border_color      " + hx(t.peach) + "\n\n"
            + "mark1_foreground " + hx(t.crust) + "\nmark1_background " + hx(t.red) + "\n"
            + "mark2_foreground " + hx(t.crust) + "\nmark2_background " + hx(t.peach) + "\n"
            + "mark3_foreground " + hx(t.crust) + "\nmark3_background " + hx(t.pink) + "\n"
    }

    // ── rofi (themes/crimson-devil.rasi) ──
    function rofiContent() {
        const t = Theme
        return "/* Auto-generated by quickshell. Do not edit by hand. */\n"
            + "* {\n"
            + "    cd-crust:    " + hx(t.crust) + ";\n"
            + "    cd-base:     " + hx(t.base) + ";\n"
            + "    cd-surface:  " + hx(t.surface1) + ";\n"
            + "    cd-text:     " + hx(t.text) + ";\n"
            + "    cd-subtext:  " + hx(t.subtext0) + ";\n"
            + "    cd-overlay:  " + hx(t.overlay0) + ";\n"
            + "    cd-dark:     " + hx(t.maroon) + ";\n"
            + "    cd-accent:   " + hx(t.mauve) + ";\n"
            + "    cd-bright:   " + hx(t.red) + ";\n"
            + "    cd-onaccent: " + hx(t.rosewater) + ";\n"
            + "    background-color: transparent;\n"
            + "    text-color:       @cd-text;\n"
            + "    font:             \"JetBrainsMono Nerd Font 11\";\n"
            + "}\n\n"
            + "window { background-color: " + hx(t.crust) + "d9; border: 2px solid; border-color: @cd-dark; border-radius: 14px; width: 600px; padding: 10px; }\n"
            + "mainbox { spacing: 8px; padding: 6px; children: [ inputbar, listview ]; }\n"
            + "inputbar { background-color: @cd-base; border-radius: 10px; padding: 10px 14px; spacing: 10px; children: [ prompt, entry ]; }\n"
            + "prompt { text-color: @cd-bright; vertical-align: 0.5; }\n"
            + "entry { placeholder: \"buscar\"; placeholder-color: @cd-overlay; text-color: @cd-text; vertical-align: 0.5; cursor: text; }\n"
            + "listview { lines: 8; columns: 1; spacing: 4px; padding: 4px 0px 0px 0px; scrollbar: false; fixed-height: false; }\n"
            + "element { padding: 9px 12px; border-radius: 8px; spacing: 12px; background-color: transparent; text-color: @cd-text; }\n"
            + "element selected { background-color: @cd-accent; text-color: @cd-onaccent; }\n"
            + "element normal active { text-color: @cd-bright; }\n"
            + "element selected active { background-color: @cd-dark; text-color: @cd-onaccent; }\n"
            + "element urgent { text-color: @cd-bright; }\n"
            + "element-icon { size: 22px; background-color: transparent; vertical-align: 0.5; }\n"
            + "element-text { background-color: transparent; text-color: inherit; vertical-align: 0.5; }\n"
            + "mode-switcher { spacing: 6px; padding: 6px 0px 0px 0px; }\n"
            + "button { padding: 6px 12px; border-radius: 8px; background-color: @cd-base; text-color: @cd-subtext; }\n"
            + "button selected { background-color: @cd-accent; text-color: @cd-onaccent; }\n"
            + "message { padding: 8px; border-radius: 8px; background-color: @cd-base; }\n"
            + "textbox { text-color: @cd-text; }\n"
    }

    // ── mango (devil-shell/theme.conf) ──
    function mangoContent() {
        const t = Theme
        return "# Auto-generated by quickshell. Do not edit by hand.\n"
            + "# Format: 0xRRGGBBAA. Apply: mmsg dispatch reload_config\n\n"
            + "rootcolor=" + mg(t.crust) + "\n"
            + "bordercolor=" + mg(t.surface1) + "\n"
            + "focuscolor=" + mg(t.red) + "\n"
            + "urgentcolor=" + mg(t.peach) + "\n"
            + "splitcolor=" + mg(t.mauve) + "\n"
            + "maximizescreencolor=" + mg(t.maroon) + "\n"
            + "scratchpadcolor=" + mg(t.surface1) + "\n"
            + "globalcolor=" + mg(t.mauve) + "\n"
            + "overlaycolor=" + mg(t.maroon) + "\n"
            + "dropcolor=0x" + rgb(t.mauve) + "55\n"
    }

    // ── vesktop (themes/devil-shell.css) — tema Vencord; habilitar 1x no Vesktop ──
    function vesktopContent() {
        const t = Theme
        return "/**\n * @name Devil Shell\n * @description Auto-generated by quickshell. Matches the shell palette.\n * @author quickshell\n */\n"
            + ":root {\n"
            + "  --background-primary: " + hx(t.base) + ";\n"
            + "  --background-secondary: " + hx(t.mantle) + ";\n"
            + "  --background-secondary-alt: " + hx(t.surface0) + ";\n"
            + "  --background-tertiary: " + hx(t.crust) + ";\n"
            + "  --background-floating: " + hx(t.crust) + ";\n"
            + "  --background-accent: " + hx(t.mauve) + ";\n"
            + "  --background-modifier-selected: " + hx(t.surface0) + ";\n"
            + "  --channeltextarea-background: " + hx(t.surface0) + ";\n"
            + "  --text-normal: " + hx(t.text) + ";\n"
            + "  --text-muted: " + hx(t.subtext0) + ";\n"
            + "  --header-primary: " + hx(t.text) + ";\n"
            + "  --header-secondary: " + hx(t.subtext1) + ";\n"
            + "  --interactive-normal: " + hx(t.subtext0) + ";\n"
            + "  --interactive-hover: " + hx(t.text) + ";\n"
            + "  --interactive-active: " + hx(t.red) + ";\n"
            + "  --brand-experiment: " + hx(t.mauve) + ";\n"
            + "  --brand-500: " + hx(t.mauve) + ";\n"
            + "  --button-positive-background: " + hx(t.mauve) + ";\n"
            + "}\n"
    }

    // ── wlogout (style.css) — grade de energia com a paleta do shell ──
    function wlogoutStyleContent() {
        const t = Theme
        const ic = "/usr/share/wlogout/icons"
        return "/* Auto-generated by quickshell. Do not edit by hand. */\n"
            + "* { background-image: none; box-shadow: none; }\n"
            + "window { background-color: " + rgbaCss(t.crust, 0.85) + "; }\n"
            + "button {\n"
            + "  color: " + hx(t.text) + ";\n"
            + "  background-color: " + hx(t.base) + ";\n"
            + "  border-style: solid;\n"
            + "  border-width: 2px;\n"
            + "  border-radius: 16px;\n"
            + "  border-color: " + hx(t.surface1) + ";\n"
            + "  background-repeat: no-repeat;\n"
            + "  background-position: center;\n"
            + "  background-size: 25%;\n"
            + "  margin: 8px;\n"
            + "}\n"
            + "button:focus, button:active, button:hover {\n"
            + "  background-color: " + hx(t.mauve) + ";\n"
            + "  color: " + hx(t.crust) + ";\n"
            + "  border-color: " + hx(t.red) + ";\n"
            + "  outline-style: none;\n"
            + "}\n"
            + "#lock     { background-image: image(url(\"" + ic + "/lock.png\")); }\n"
            + "#logout   { background-image: image(url(\"" + ic + "/logout.png\")); }\n"
            + "#suspend  { background-image: image(url(\"" + ic + "/suspend.png\")); }\n"
            + "#hibernate{ background-image: image(url(\"" + ic + "/hibernate.png\")); }\n"
            + "#reboot   { background-image: image(url(\"" + ic + "/reboot.png\")); }\n"
            + "#shutdown { background-image: image(url(\"" + ic + "/shutdown.png\")); }\n"
    }

    // ── wlogout (layout) — botões e ações. Estático (não depende de cor), mas
    // reescrito junto p/ garantir que o wlogout tenha config (o sistema não traz
    // layout padrão). Lock = swaylock (tema escuro do shell). Sair = mmsg quit. ──
    function wlogoutLayoutContent() {
        return "{ \"label\": \"lock\",      \"action\": \"sh -c 'pidof swaylock || swaylock'\", \"text\": \"Bloquear\",  \"keybind\": \"l\" }\n"
            + "{ \"label\": \"logout\",    \"action\": \"mmsg dispatch quit\",                  \"text\": \"Sair\",      \"keybind\": \"e\" }\n"
            + "{ \"label\": \"suspend\",   \"action\": \"systemctl suspend\",                   \"text\": \"Suspender\", \"keybind\": \"u\" }\n"
            + "{ \"label\": \"hibernate\", \"action\": \"systemctl hibernate\",                 \"text\": \"Hibernar\",  \"keybind\": \"h\" }\n"
            + "{ \"label\": \"reboot\",    \"action\": \"systemctl reboot\",                    \"text\": \"Reiniciar\", \"keybind\": \"r\" }\n"
            + "{ \"label\": \"shutdown\",  \"action\": \"systemctl poweroff\",                  \"text\": \"Desligar\",  \"keybind\": \"s\" }\n"
    }

    // ── swaylock (config) — tela de bloqueio com a paleta do shell ──
    // ATENCAO: o swaylock NAO aceita comentario no fim de linha de opcao (vira valor).
    function swaylockContent() {
        const t = Theme
        return "# Auto-generated by quickshell. Do not edit by hand. Format: RRGGBBAA.\n"
            + "screenshots\n"
            + "effect-blur=7x5\n"
            + "effect-vignette=0.5:0.5\n"
            + "fade-in=0.3\n"
            + "grace=2\n"
            + "grace-no-mouse\n"
            + "indicator-idle-visible\n"
            + "ignore-empty-password\n"
            + "clock\n"
            + "timestr=%H:%M\n"
            + "datestr=%a %d %b\n"
            + "indicator\n"
            + "indicator-radius=110\n"
            + "indicator-thickness=8\n"
            + "font=JetBrainsMono Nerd Font\n"
            + "font-size=26\n"
            + "color=" + sl(t.crust) + "\n"
            + "inside-color=" + sl(t.base, "cc") + "\n"
            + "inside-clear-color=" + sl(t.surface0, "cc") + "\n"
            + "inside-ver-color=" + sl(t.maroon, "cc") + "\n"
            + "inside-wrong-color=" + sl(t.red, "cc") + "\n"
            + "inside-caps-lock-color=" + sl(t.surface0, "cc") + "\n"
            + "ring-color=" + sl(t.mauve) + "\n"
            + "ring-clear-color=" + sl(t.maroon) + "\n"
            + "ring-ver-color=" + sl(t.peach) + "\n"
            + "ring-wrong-color=" + sl(t.red) + "\n"
            + "ring-caps-lock-color=" + sl(t.yellow) + "\n"
            + "line-uses-inside\n"
            + "key-hl-color=" + sl(t.peach) + "\n"
            + "bs-hl-color=" + sl(t.red) + "\n"
            + "caps-lock-key-hl-color=" + sl(t.peach) + "\n"
            + "caps-lock-bs-hl-color=" + sl(t.red) + "\n"
            + "separator-color=00000000\n"
            + "text-color=" + sl(t.text) + "\n"
            + "text-clear-color=" + sl(t.text) + "\n"
            + "text-ver-color=" + sl(t.text) + "\n"
            + "text-wrong-color=" + sl(t.text) + "\n"
            + "text-caps-lock-color=" + sl(t.text) + "\n"
    }

    // Regenera TODOS os arquivos externos (backup + escrita + reload ao vivo).
    function exportAll() {
        const HOME = Quickshell.env("HOME")
        const targets = [
            { path: HOME + "/.config/kitty/themes/crimson-devil.conf", content: kittyContent() },
            { path: HOME + "/.config/rofi/themes/crimson-devil.rasi",  content: rofiContent() },
            { path: HOME + "/.config/mango/devil-shell/theme.conf",     content: mangoContent() },
            { path: HOME + "/.config/vesktop/themes/devil-shell.css",   content: vesktopContent() },
            { path: HOME + "/.config/wlogout/style.css",                content: wlogoutStyleContent() },
            { path: HOME + "/.config/wlogout/layout",                   content: wlogoutLayoutContent() },
            { path: HOME + "/.config/swaylock/config",                  content: swaylockContent() }
        ]
        let script = "set -e\nts=$(date +%Y%m%d-%H%M%S)\n"
        for (let i = 0; i < targets.length; i++) {
            const p = targets[i].path
            const dir = p.substring(0, p.lastIndexOf("/"))
            const b64 = Qt.btoa(targets[i].content)   // base64 = só [A-Za-z0-9+/=], seguro entre aspas
            script += "mkdir -p '" + dir + "'\n"
            script += "[ -f '" + p + "' ] && cp -f '" + p + "' '" + p + ".bak-'$ts || true\n"
            script += "printf %s '" + b64 + "' | base64 -d > '" + p + "'\n"
        }
        // recarrega ao vivo (Process herda o env -> mmsg acha o socket do mango)
        script += "command -v mmsg >/dev/null && mmsg dispatch reload_config || true\n"
        script += "pkill -USR1 -x kitty 2>/dev/null || true\n"
        script += "command -v notify-send >/dev/null && notify-send -a 'Devil Shell' 'Temas regenerados' 'kitty / rofi / mango / vesktop / wlogout / swaylock' || true\n"
        proc.exec(["sh", "-c", script])
    }

    Process { id: proc }
}
